In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv("healthy_eating_balanced.csv",index_col=None)

In [4]:
dataset

,meal_id,meal_name,cuisine,meal_type,calories,protein_g,carbs_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,cooking_method,rating,is_healthy
0,662,Employee Rice,Japanese,Breakfast,357,55.5,39.1,53.1,8.0,0.7,1117,274,Raw,3.7,0
1,1170,Animal Pasta,Mexican,Dinner,328,60.2,40.9,2.7,9.9,5.3,799,136,Raw,3.6,1
2,1602,Be Pasta,Mediterranean,Snack,232,79.0,31.3,4.3,27.2,10.5,326,206,Fried,1.9,1
3,923,Car Rice,American,Dinner,652,41.3,0.6,7.5,25.2,15.9,1602,22,Boiled,3.6,1
4,1154,Real Pasta,Chinese,Lunch,125,68.3,105.9,10.0,16.4,9.8,329,73,Roasted,1.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3621,1241,Hour Rice,Japanese,Dinner,194,37.3,113.8,31.8,7.3,31.6,509,221,Baked,3.8,0
3622,1431,Agree Salad,Chinese,Dinner,233,75.3,67.5,53.5,12.4,9.7,280,44,Steamed,1.3,0
3623,949,Military Salad,Italian,Snack,1149,24.6,18.5,45.9,10.1,48.2,1664,91,Boiled,1.4,0
3624,885,Serious Wrap,Mediterranean,Lunch,287,62.3,13.6,17.3,0.5,10.3,2434,118,Fried,3.9,1
3625,778,Itself Salad,Japanese,Lunch,395,63.6,114.0,0.8,7.3,4.0,247,28,Grilled,4.2,1

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
indep=dataset[['calories', 'carbs_g', 'fat_g', 'sugar_g', 'sodium_mg']]
dep=dataset['is_healthy']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [9]:
param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [10]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test_) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [11]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 10}

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001994,0.000630,0.000000,0.000000e+00,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.003191,0.002918,0.000000,0.000000e+00,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.048269,0.003918,0.010373,1.738762e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.0,1.0,1.0,1.000000,1.0,1.000000,0.000000,1
3,0.398334,0.005109,0.027925,8.921235e-04,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.0,1.0,1.0,0.997938,1.0,0.999588,0.000825,4
4,0.042685,0.001466,0.008378,4.881691e-04,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.0,1.0,1.0,1.000000,1.0,1.000000,0.000000,1
5,0.402324,0.002863,0.027526,4.888117e-04,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.0,1.0,1.0,0.997938,1.0,0.999588,0.000825,4
6,0.001196,0.000398,0.000000,0.000000e+00,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001197,0.000399,0.000000,0.000000e+00,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.046475,0.001493,0.008778,7.455907e-04,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.0,1.0,1.0,0.997938,1.0,0.999588,0.000825,4
9,0.433756,0.004444,0.026729,3.987318e-04,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.0,1.0,1.0,0.997938,1.0,0.999588,0.000825,4
10,0.046674,0.000746,0.007979,8.740569e-07,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",1.0,1.0,1.0,1.000000,1.0,1.000000,0.000000,1
11,0.337311,0.024651,0.017354,1.492630e-03,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.0,1.0,1.0,0.997938,1.0,0.999588,0.000825,4

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 10}: 1.0

In [15]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[607   0]
 [  0 602]]

In [16]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       607
           1       1.00      1.00      1.00       602

    accuracy                           1.00      1209
   macro avg       1.00      1.00      1.00      1209
weighted avg       1.00      1.00      1.00      1209

In [17]:
table_pr=pd.DataFrame()

In [18]:
print(X_test)

      calories  carbs_g  fat_g  sugar_g  sodium_mg
227        233    123.7    8.1      8.8        982
2297       218     60.5   16.3      8.2        713
971        195     72.8   19.3      5.6         60
3491       959     64.5   31.4     11.7        109
2552       232     74.5    7.0     14.8       1433
...        ...      ...    ...      ...        ...
1061       545     96.3    9.8     16.0        233
997        122    110.3    8.9      3.0        869
3490       691    137.2   18.7      0.0       2424
3013       454     28.1   55.3     27.5       1255
1427       138     44.8   22.3      9.7       2271

[1209 rows x 5 columns]

In [19]:
table_pr['calories']=X_test["calories"]
table_pr['carbs_g']=X_test["carbs_g"]
table_pr['fat_g']=X_test["fat_g"]
table_pr['sugar_g']=X_test["sugar_g"]
table_pr['sodium_mg']=X_test["sodium_mg"]

table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

In [20]:
table_pr = X_test.copy()

table_pr['Actual'] = y_test
table_pr['Predicted'] = grid_predictions

In [21]:
table_pr.head(1500)

      calories  carbs_g  fat_g  sugar_g  sodium_mg  Actual  Predicted
227        233    123.7    8.1      8.8        982       1          1
2297       218     60.5   16.3      8.2        713       1          1
971        195     72.8   19.3      5.6         60       1          1
3491       959     64.5   31.4     11.7        109       0          0
2552       232     74.5    7.0     14.8       1433       1          1
...        ...      ...    ...      ...        ...     ...        ...
1061       545     96.3    9.8     16.0        233       1          1
997        122    110.3    8.9      3.0        869       1          1
3490       691    137.2   18.7      0.0       2424       1          1
3013       454     28.1   55.3     27.5       1255       0          0
1427       138     44.8   22.3      9.7       2271       1          1

[1209 rows x 7 columns]

In [22]:
table_pr.to_csv("cm.csv",index=False)

In [23]:
calories_input=float(input("calories:"))
carbs_g_input=float(input("carbs_g:"))
fat_g_input=float(input("fat_g:"))
sugar_g_input=float(input("sugar_g:"))
sodium_mg_input=float(input("sodium_mg:"))

calories:138
carbs_g:44.8
fat_g:22.3
sugar_g:9.7
sodium_mg:2271

In [25]:
Future_Prediction=grid.predict([[calories_input, carbs_g_input, fat_g_input, sugar_g_input, sodium_mg_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[0]